### ISSUE TITLE
[BRIDGE BookClub] First OT 2023-03-29 

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_BookClub#1]
# BRIDGE BookClub

안녕하세요..! 많은 분들이 지원해주셔서 Repo까지 개설하게 되었습니다..! 

참여를 희망하시는 분은 아래 `게더타운`에 2023-03-29 22:00까지 입장해주시면 됩니다.

- https://app.gather.town/invite?token=NQacK4zfQnezkEqOlxZB

## OT 내용

1. 자기소개
2. 북 클럽이란?
3. 작업 방식 소개(PR, Discssion)
4. 시간 선정, 책 선정
5. 마무리

*짧게 20분 정도 진행될 예정입니다. 참여하신 분이 정해진 책과 시간이 가능하시다면 OT가 끝난 뒤 레포에 초대해드립니다.*

**Comment by hellog2n** [comment]
다음 모임 : 4/13 목요일 오후 10시 `(약 2시간 소요 예정)`
* Clean Code 책 1-3장 읽고 리뷰 및 논의사항 작성
