### ISSUE TITLE
<Clean Code> 4장 ~ 8장, 2023-05-04

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_BookClub#10]
# Clean Code  

* 4장 주석
* 5장 형식 맞추기
* 6장 객체와 자료 구조
* 7장 오류 처리
* 8장 경계

해당 주차의 내용을 읽고 리뷰 내용을 자유 서식으로 Pull requests 생성

*.md형식의 파일을 많이 사용하는 것 같습니다.(참고)*

* 브랜치이름은 자신의 이름/진행중인 책으로 사용(ex) jeonglee/CleanCode)

## Required

* 각 챕터별로 1개 이상 논의 내용을 작성 (자유 형식)
* Reviewer는 자신을 제외하고 나머지 멤버를 할당
* 멤버 전원이 리뷰어로 등록되기 때문에 총 멤버가 5명일 경우 4명의 풀리퀘를 리뷰

*approve를 해주셔야 병합이 됩니다.*

## Optional

* 각 챕터별로 책 내용 정리, 추가 논의, 질문, 공유하고 싶은 정보, 생각을 정리
* 말씀드린 대로 참여는 강제가 아닙니다.

## Discussion

* 논의는 게더타운에서 OT와 같은 형식으로 진행
* 풀리퀘 순서로 파트를 분배 후 이야기를 시작

## ETC

모임이 5월 4일이니 최소 3일 전까지 풀리퀘 부탁드립니다..

**Comment by FrenzyNight** [comment]
이번엔 일정이 조금 바빠서 참여 못할 것 같습니다.

**Comment by ccmuk58** [comment]
큰 일이 조금 많이 생겨서 앞으로 스터디 진행에 조금 무리가 있을 듯 합니다,, 죄송합니다 !! 😭

**Comment by hellog2n** [comment]
독서는 완료 하였으나, 오늘밤부터 새벽까지 연구실내 서버일이 급하게 잡혀서 참여가 불가능할 것 같습니다... 다음번에 참여하겠습니다!

**Comment by fkdl0048** [comment]
확인했습니다..! 초반에 말씀드린 것처럼 절대 불참에 대해 부담 받지 않으셔도 됩니다..!

반대로 언제든지 다시 참여 가능하니 편하게 말씀해주세요!
