### ISSUE TITLE
[BRIDGE BookClub] 2nd OT, 2023-07-20 [22:00]

### ISSUE THREAD

**Issue by fkdl0048** [BRIDGE-DEV/BRIDGE_BookClub#31]
# BRIDGE BookClub 2nd OT

안녕하세요 1회차를 무사히 마치고 2회차로 돌아왔습니다!

참여를 희망하시는 분들은 아래 코멘트를 달아주세요.

기존 게더타운 방식에서 **디스코드**로 변경되었습니다.

## OT 내용

1. 자기소개
2. 북 클럽 소개
3. 책 리뷰 방식 설명
4. 모임 시간, 책 분량 설정
5. 마무리

*OT는 짧게 20분 정도로 진행됩니다. OT설명 이후 참여의사가 있으신 분들을 레포에 초대드립니다.*

2회차 선정 책 [리팩터링](https://www.yes24.com/Product/Goods/89649360)

[OT참여 링크](https://app.gather.town/invite?token=xpUR61KzT6adwyLmbsAC)

**Comment by NearthYou** [comment]
참여 원합니다!

**Comment by yeum** [comment]
참여합니다 ㅎ

**Comment by kkwoo94517** [comment]
참여 희망합니다!

**Comment by MakerJun46** [comment]
참여 희망합니다.

**Comment by yeonmo57** [comment]
참여 희망합니다 :)

**Comment by fkdl0048** [comment]
[OT참여 링크](https://app.gather.town/invite?token=xpUR61KzT6adwyLmbsAC)

**Comment by Eatqua** [comment]
> 20일 시간도 정해졌을까요 ?

**Comment by fkdl0048** [comment]
넵! 22시입니다

- #31
